/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Photocategory = "ABSTRACT" | "ASTROPHOTOGRAPHY" | "MOON" | "NATURE" | "OTHER" | "SKY" | "STREET" | "WARM";

export type Photostatus = "APPROVED" | "PENDING";

export type Role = "ADMIN" | "USER";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  access_token: string | null;
  expires_at: number | null;
  id: string;
  id_token: string | null;
  provider: string;
  providerAccountId: string;
  refresh_token: string | null;
  scope: string | null;
  session_state: string | null;
  token_type: string | null;
  type: string;
  userId: string;
}

export interface Comment {
  body: string;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  photoId: number;
  userId: string;
}

export interface Follows {
  createdAt: Generated<Timestamp>;
  followerId: string;
  followingId: string;
}

export interface Like {
  anonymousToken: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  photoId: number;
  userId: string | null;
}

export interface Message {
  createdAt: Generated<Timestamp>;
  id: string;
  isRead: Generated<boolean>;
  receiverId: string;
  senderId: string;
  text: string;
}

export interface Otptoken {
  createdAt: Generated<Timestamp>;
  email: string;
  expires: Timestamp;
  failedAttempts: Generated<number>;
  id: string;
  ipAddress: string | null;
  token: string;
}

export interface Photo {
  aperture: string | null;
  authorName: string | null;
  camera: string | null;
  category: Generated<Photocategory>;
  coordinates: string | null;
  createdAt: Generated<Timestamp>;
  focalLength: string | null;
  id: Generated<number>;
  iso: number | null;
  location: string | null;
  shutter: string | null;
  status: Generated<Photostatus>;
  title: string;
  updatedAt: Generated<Timestamp>;
  url: string;
  userId: string | null;
  views: Generated<number>;
}

export interface Rating {
  anonymousToken: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  photoId: number;
  updatedAt: Timestamp;
  userId: string | null;
  value: number;
}

export interface Session {
  expires: Timestamp;
  id: string;
  sessionToken: string;
  userId: string;
}

export interface User {
  customImage: string | null;
  email: string | null;
  emailVerified: Timestamp | null;
  id: string;
  image: string | null;
  name: string | null;
  role: Generated<Role>;
  telegramId: string | null;
  telegramUsername: string | null;
}

export interface VerificationToken {
  expires: Timestamp;
  identifier: string;
  token: string;
}

export interface DB {
  Account: Account;
  Comment: Comment;
  Follows: Follows;
  Like: Like;
  Message: Message;
  otptoken: Otptoken;
  Photo: Photo;
  Rating: Rating;
  Session: Session;
  User: User;
  VerificationToken: VerificationToken;
}
